on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools any::RcppGSL any::rmarkdown any::tinytex any::pkgdown
      - name: Install package
        run: R CMD INSTALL .
      - name: Build and deploy pkgdown site
        run: |
          devtools::document()
          rmarkdown::render('README.Rmd', output_format = 'md_document')
          pkgdown::build_site(lazy = FALSE)
          rmarkdown::render('README.Rmd', output_format = 'github_document')
          document <- paste(readLines('README.md'), collapse = "\n")
          document <- gsub("<!-- badges: start -->", '<img src="man/figures/logo.png" align="right" height="48"/>\n<!-- badges: start -->', document)
          document <- gsub('"\n.*?\n"', '', document)
          document <- gsub('\n".*?gamma"', '', document)
          document <- gsub('\n"\\(DA\\)"', '', document)
          document <- gsub('\n"\\(DM\\)"', '', document)
          document <- gsub("<iframe.+?iframe>", '<a style="display:block;margin:auto" href="https://www.youtube.com/watch?v=Kkjkny94dgU" target="_blank"><img src="http://img.youtube.com/vi/Kkjkny94dgU/0.jpg"  alt="Session Recording" width="560" height="315" border="10" /></a>', document)
          writeLines(document, 'README.md')
          devtools::document()
        shell: Rscript {0}

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: docs/
          server-dir: ${{ secrets.ftp_server_dir }}
